version: "3.9"

networks:
  reactive-network:
    driver: bridge

volumes:
  pgdata:
  pgadmin-data:
  kafka-data:

services:
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    networks:
      - reactive-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: REACTIVE_DB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin4:
    image: dpage/pgadmin4:8
    container_name: pgadmin4
    networks:
      - reactive-network
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8091:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres-db
    restart: unless-stopped

  kafka:
    image: apache/kafka:4.2.0
    container_name: kafka
    networks:
      - reactive-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka-data:/tmp/kraft-combined-logs
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks:
      - reactive-network
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    restart: unless-stopped

#  reactive-app:
#    image: reactive-app
#    container_name: reactive-app
#    networks:
#      - reactive-network
#    environment:
#      SPRING_R2DBC_URL: r2dbc:postgresql://postgres-db:5432/REACTIVE_DB
#      SPRING_R2DBC_USERNAME: postgres
#      SPRING_R2DBC_PASSWORD: postgres
#    ports:
#      - "8089:8089"
#    depends_on:
#      - 'postgres-db'
#    restart: unless-stopped
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8089/actuator/health" ]
#      interval: 15s
#      timeout: 5s
#      retries: 5
#      start_period: 30s
#    deploy:
#      replicas: 1
#      restart_policy:
#        condition: on-failure