spring:
  config:
    activate:
      on-profile: prod

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:prod-db-host}:${DB_PORT:5432}/${DB_NAME:PROD_DB}
    username: ${DB_USERNAME:prod_user}
    password: ${DB_PASSWORD:prod_password}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
  sql:
    init:
      mode: never

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:kafka-prod1:9092,kafka-prod2:9092,}
    producer:
      acks: all
      retries: 10
      batch-size: 32768
      linger-ms: 10
      compression-type: snappy
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 120000
        spring.json.add.type.headers: true  # Allows multiple event types
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 500
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"          # Accept all packages
        spring.json.use.type.headers: true         # Read event type from headers
        isolation.level: read_committed
    listener:
      ack-mode: manual
      type: single

logging:
  level:
    root: WARN
    com.reactive: INFO
  file:
    name: /var/log/myapp/myapp.log